#ifndef WEB_CONFIG_H
#define WEB_CONFIG_H

static const char WEB_CONFIG_HTML[] =
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>ESP32-CAM</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{background:#000;color:#ccc;font:14px/1.5 -apple-system,sans-serif;display:flex;min-height:100dvh;padding:24px}"
".c{background:#111;border:1px solid #222;border-radius:12px;padding:28px;width:100%;max-width:360px;margin:auto}"
"h1{font-size:17px;font-weight:600;color:#eee;margin-bottom:24px}"
"label{display:block;font-size:12px;color:#666;margin-bottom:4px}"
"input{display:block;width:100%;padding:10px 12px;background:#0a0a0a;border:1px solid #222;border-radius:8px;color:#eee;font-size:14px;outline:none;margin-bottom:16px}"
"input:focus{border-color:#555}"
".btn{display:block;width:100%;padding:10px;background:#fff;color:#000;border:none;border-radius:8px;font-size:14px;font-weight:500;cursor:pointer}"
".btn:active{opacity:.8}"
".st{font-size:13px;padding:8px 0;margin-top:12px;display:none;text-align:center}"
".ok{color:#4ade80;display:block}"
".er{color:#f87171;display:block}"
".wa{color:#fbbf24;display:block}"
"</style>"
"</head><body>"
"<div class='c'>"
"<h1>Connect WiFi</h1>"
"<label>Network</label>"
"<input id='ssid' placeholder='SSID' />"
"<label>Password</label>"
"<input id='pwd' type='password' placeholder='password' />"
"<button class='btn' onclick='connect()'>Connect</button>"
"<div id='s' class='st'></div>"
"</div>"
"<script>"
"function e(id){return document.getElementById(id)}"
"function st(m,t){var x=e('s');x.textContent=m;x.className='st '+t}"
"async function connect(){"
"var ss=e('ssid').value,pw=e('pwd').value;"
"if(!ss){st('enter SSID','er');return}"
"st('connecting...','wa');"
"try{"
"var r=await fetch('/api/wifi/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:ss,password:pw})});"
"var j=await r.json();"
"if(j&&j.ok){st('connected! switching...','ok')}"
"else{st('failed: '+(j.msg||'error'),'er')}"
"}catch(e){st('error: '+e.message,'er')}"
"}"
"</script>"
"</body></html>";

#endif