#ifndef WEB_CONFIG_H
#define WEB_CONFIG_H

static const char WEB_CONFIG_HTML[] =
"<!DOCTYPE html>"
"<html lang='zh-CN'>"
"<head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>ESP32-CAM WiFi</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box;font-family:sans-serif}"
"body{background:#0f0f23;color:#fff;display:flex;justify-content:center;align-items:center;min-height:100vh;padding:20px}"
".c{background:#1a1a3e;border-radius:16px;padding:30px;width:100%;max-width:400px}"
"h1{text-align:center;font-size:20px;margin-bottom:20px}"
"label{font-size:13px;color:#aaa;display:block;margin:8px 0 4px}"
"input{width:100%;padding:12px;border-radius:10px;border:1px solid #333;background:#0f0f23;color:#fff;font-size:15px;margin-bottom:12px}"
".btn{width:100%;padding:14px;border:none;border-radius:12px;font-size:16px;cursor:pointer;margin:6px 0;background:#6c5ce7;color:#fff}"
".st{padding:12px;border-radius:10px;margin:12px 0;font-size:14px;display:none}"
".ok{border:1px solid #00b894;display:block}"
".er{border:1px solid #e17055;display:block}"
".wa{border:1px solid #fdcb6e;display:block}"
"</style>"
"</head><body>"
"<div class='c'>"
"<h1>连接 WiFi</h1>"
"<div id='s' class='st'></div>"
"<label>WiFi SSID</label>"
"<input id='ssid' placeholder='输入 WiFi 名称' />"
"<label>密码</label>"
"<input id='pwd' type='password' placeholder='输入 WiFi 密码' />"
"<button class='btn' onclick='connect()'>Connect</button>"
"<div style='margin-top:16px;padding-top:12px;border-top:1px solid #333'>"
"<p style='font-size:12px;color:#666;text-align:center' id='info'>等待连接...</p>"
"</div>"
"</div>"
"<script>"
"function st(m,t){var e=document.getElementById('s');e.textContent=m;e.className='st '+t}"
"async function connect(){"
"var ss=document.getElementById('ssid').value;"
"var pw=document.getElementById('pwd').value;"
"if(!ss){st('请输入 WiFi 名称','er');return}"
"st('连接中...','wa');"
"try{"
"var r=await fetch('/api/wifi/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:ss,password:pw})});"
"var j=await r.json();"
"if(j&&j.ok){st('连接成功！正在切换到新网络...','ok')}"
"else{st('连接失败: '+(j.msg||'未知错误'),'er')}"
"}catch(e){st('请求失败: '+e.message,'er')}"
"}"
"async function load(){"
"try{"
"var r=await fetch('/api/wifi/status');"
"var j=await r.json();"
"if(j)document.getElementById('info').textContent='模式: '+(j.mode||'--')+' | IP: '+(j.ip||'--')"
"}catch(e){}"
"}"
"load()"
"</script>"
"</body></html>";

#endif